openldap:
  env:
    LDAP_ORGANISATION: "Mays-Demo"
    LDAP_DOMAIN: "mays-demo.com"
  adminPassword: admin
  configPassword: config
  persistence:
    enabled: true
  phpldapadmin:
    enabled: true
    ingress:
      enabled: true
      hosts: 
      - phpldapadmin.apps.mays-demo.sandbox2140.opentlc.com
    env:
      PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
  ltb-passwd:
    ingress:
      enabled: true
      hosts: 
      - ltb-passwd.apps.mays-demo.sandbox2140.opentlc.com
