openldap:
  env:
    LDAP_ORGANISATION: "Mays-Demo"
    LDAP_DOMAIN: "mays-demo.com"
  adminPassword: admin
  configPassword: config
  persistence:
    enabled: true
  phpldapadmin:
    enabled: true
    ingress:
      enabled: true
      ingressClassName:
      path: /
    env:
      PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
